TE2116 no longer trust everything as html
SynergyDataSystems/angucomplete-alt pull request #11
Opened 2022-03-02 21:06 UTC by caxter99

2022-03-02 22:33 UTC, jkulton commented
![whomst](https://user-images.githubusercontent.com/6694167/156452741-28c1cd01-6c8a-401b-b564-dc5f70447a52.png)

2022-03-04 01:20 UTC, DougKeller requested changes

2022-03-04 01:20 UTC, DougKeller commented on build/merged_templates.js
> +(function(module) {
these build files are temporary and can be removed with `gulp clean`

2022-03-04 01:36 UTC, coreyconley commented
> ![whomst](https://user-images.githubusercontent.com/6694167/156452741-28c1cd01-6c8a-401b-b564-dc5f70447a52.png)

Lol this bad boy is getting a lot of mileage.

2022-03-04 18:12 UTC, DougKeller commented
> Lol this bad boy is getting a lot of mileage.

angucomplete-alt will never die :joy: always nice to see you guys stop by @jkulton @coreyconley

2022-03-04 18:13 UTC, DougKeller approved these changes

2022-03-08 16:05 UTC, merged